### ISSUE TITLE
Enabling ADFS Relay State for Windows Server 2016 and above

### ISSUE THREAD

**Issue by saltysoup** [awsdocs/aws-management-portal-for-vcenter-user-guide#1]
To enable Relay State for ADFS in Windows Server 2016 and above (soon 2017), editing the %systemroot%\ADFS\Microsoft.IdentityServer.Servicehost.exe.config file no longer works as this has been moved to powershell.

``` powershell
import ADFS
Set-AdfsProperties -EnableRelayStateForIdpInitiatedSignOn $true
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
